package com.epam.sm.example.model;

public enum OrderState {
    CREATED,
    SUBMITTED,
    PAID,
    PROCESSING,
    MAIL_DELIVERY,
    SERVICE_DELIVERY,
    DELIVERY_TO_SHOP,
    DELIVERED,
    FULFILLED,
    CANCELLED,

    DELIVERY_CHOICE,

    FORK_PROCESSING,
    JOIN_PACKAGED,
    PACKAGED,
    PR_1_BOOKING_THINGS,
    PR_1_BOOKED_THINGS,

    PR_2_ORDERING_THINGS,
    PR_2_ORDERED_THINGS,
    PR_2_WAITING_THINGS,
    PR_2_DELIVERED_THINGS
}
